spring:
  application:
    name: szamlazzponthu-test-app

  datasource:
    url: jdbc:h2:mem:usrdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: ${BN_DB_USER:test}
    password: ${BN_DB_PASS:test}
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    schemas: test
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc.time_zone: UTC
        default_schema: test
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
