/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package test.szamlazz.hu.api.interfaces;

import test.szamlazz.hu.api.dto.JobType;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "JobTypes", description = "the JobTypes API")
public interface JobTypesApi {

    /**
     * GET /job-types : Elérhető JobType értékek listázása
     * Visszaadja a rendszerben engedélyezett munkakör enumokat.
     *
     * @return JobType lista (status code 200)
     */
    @Operation(
        operationId = "jobTypesGet",
        summary = "Elérhető JobType értékek listázása",
        description = "Visszaadja a rendszerben engedélyezett munkakör enumokat.",
        tags = { "JobTypes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "JobType lista", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = JobType.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/job-types",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<JobType>> _jobTypesGet(
        
    );

}
