CREATE SCHEMA IF NOT EXISTS test;

CREATE TABLE job_type (
  code VARCHAR(16) PRIMARY KEY,
  label_hu VARCHAR(64) NOT NULL,
  label_en VARCHAR(64) NOT NULL
);

INSERT INTO job_type(code, label_hu, label_en) VALUES
 ('KERTESZ','Kertész','Gardener'),
 ('HENTES','Hentes','Butcher'),
 ('PEK','Pék','Baker');

CREATE TABLE IF NOT EXISTS usr (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname VARCHAR(64) NOT NULL,
  lastname  VARCHAR(64) NOT NULL,
  address   VARCHAR(128),
  telephone VARCHAR(128),
  active    BOOLEAN NOT NULL,
  job       VARCHAR(16) NOT NULL
);

ALTER TABLE usr
  ADD CONSTRAINT fk_usr_job
  FOREIGN KEY (job) REFERENCES job_type(code);

INSERT INTO usr (firstname, lastname, address, telephone, active, job)
VALUES
  ('Gipsz', 'Jakab', '1025 Budapest, Fő u. 1.', '+36 30 123 4567', TRUE, 'PEK'),
  ('Kovács', 'Mária', '1033 Budapest, Lajos u. 88.', '+36 70 234 5678', TRUE, 'HENTES'),
  ('Tóth', 'József', '1117 Budapest, Irinyi J. u. 42.', '+36 20 345 6789', FALSE, 'KERTESZ'),
  ('Kovács', 'Anna', '1132 Budapest, Váci út 22.', '+36 31 456 7890', TRUE, 'KERTESZ');
