name: Local Docker build on push

on:
  push:
    branches: [ main, master ]

# NINCS szükség id-tokenre, secretekre, loginra
permissions:
  contents: read

jobs:
  build-local-image:
    # legyenek olyan címkék a runneren, amiket itt megadsz
    runs-on: [self-hosted, linux, docker]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx (opcionális, de gyorsít a cache miatt)
        uses: docker/setup-buildx-action@v3

      - name: Build local image (no push)
        run: |
          APP=szamlazz-be
          TAG=latest
          BUILD_ARGS=""
          docker build -f Dockerfile -t "${APP}:${TAG}" $BUILD_ARGS .
